### ISSUE TITLE
Fluxograma

### ISSUE THREAD

**Issue by NicolasCBV** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-senectus#23]
Criar um fluxograma para auxiliar a dupla de design na montagem dos wireframes e telas.

**Comment by NicolasCBV** [comment]
Fluxograma esta pronto e pode ser visto por [aqui](https://lucid.app/lucidchart/9076bda7-49ab-4e7c-b1c1-ba1dcbf0172d/edit?invitationId=inv_8794d23c-0657-498e-a963-06f6538b7030&page=0_0#).

**Comment by HermesMAPLima** [comment]
Ok @NicolasCBV . Este é o fluxograma que revisamos em reunião Domingo passado.
