### ISSUE TITLE
Realizar correção dos documentos da etapa 1

### ISSUE THREAD

**Issue by NicolasCBV** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-senectus#26]
@HermesMAPLima recomendo que acesse o canvas da PUC para verificar as notas de correção da Luciana e sugestões realizadas pela mesma. Assim que possível, entrarei em contato com você para te auxiliar nesta tarefa, caso necessário.

**Comment by HermesMAPLima** [comment]
Sim, tenho de fazer a correção com base nas críticas que a Luciana nos fez em uns 2 ou 3 conceitos.

**Comment by HermesMAPLima** [comment]
Boa tarde. Efetuada mudança do quadro comparativo de produtos similares que estava na "Introdução" para a "justificativa".

**Comment by HermesMAPLima** [comment]
Efetuada alterações: 
1. No card da persona João da Silva;
2. Na história dos usuários;
3. Movemos o quadro comparativo da "introdução" para a "justificativa";
4. Alteração nas restrições do projeto.
